name: Artifact Upload and Download

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  artifact-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create text file
      run: echo "Hello World" > hello.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact

    - name: Print file content
      run: cat hello.txt